services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: php-apache-proyecto
    ports:
      - "8081:80"
    volumes:
      - ./app/proyectoFinal:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-proyecto
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: centro_diurno
      MYSQL_USER: Pruebas
      MYSQL_PASSWORD: Pruebas123
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-proyecto
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: Pruebas
      PMA_PASSWORD: Pruebas123
    ports:
      - "8083:80"

volumes:
  db_data: